# Spring Application Server Configurations
spring:
  application:
    name: secure-redis-proxy

  profiles:
    active: dev

---
#Dev settings
spring:
  profiles: dev

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: keystores/redis-proxy-api.p12
    key-store-password: redis-proxy-api
    key-alias: redis-proxy-api

security:
  require-ssl: true
