# Spring Application Server Configurations
spring:
  application:
    name: secure-redis-proxy

  profiles:
    active: dev

---
#Dev settings
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: keystores/redis-proxy-api.p12
    key-store-password: redis-proxy-api
    key-alias: redis-proxy-api

security:
  require-ssl: true

keycloak:
  realm: master
  auth-server-url: http://localhost:8888/auth
  resource: test-backend
  principal-attribute: preferred_username
  bearer-only: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
