# Spring Application Server Configurations
spring:
  application:
    name: secure-redis-proxy

  profiles:
    active: dev

---
#Dev settings
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: keystores/redis-proxy-api.p12
    key-store-password: redis-proxy-api
    key-alias: redis-proxy-api

security:
  require-ssl: true

keycloak:
  realm: thesis-realm
  auth-server-url: http://localhost:8888/auth
  resource: thesis-redis-backend
  principal-attribute: preferred_username
  bearer-only: true

---
#Dev settings
spring:
  profiles: prod
  main:
    allow-bean-definition-overriding: true

server:
  port: 8777
  ssl:
    key-store-type: PKCS12
    key-store: production-keystores/proxy-api.p12
    key-store-password: wLgz8_tChXhhH-UwezGLL38wr
    key-alias: redis-proxy-api

security:
  require-ssl: true

keycloak:
  realm: thesis-realm
  auth-server-url: https://ns31249243.ip-51-210-0.eu:8678/auth
  resource: thesis-redis-backend
  principal-attribute: preferred_username
  bearer-only: true
  trust-store: production-keystores/proxy-api-truststore.p12
  truststore-password: qTn-Mo@j46f9ddNbHjwtxA3y.
